### ISSUE TITLE
Escaping paths in GUI

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#127]
Under Windows, a `recipy gui` search for `C:\Users\mjj\deployment\file` fails, but succeeds for `C:\\Users\\mjj\\deployment\\file`. Update the search code to escape \ in file paths.

via @mikej888

**Comment by trbedwards** [comment]
Should now work for windows style paths without doubling-up on the backslashes. I solved this using `query = re.escape(query)` which appends extra backslashes to the colons as well as the backslashes themselves.

However, these double backslashes are displayed in the search box after performing a search, which a little annoyance. I can't pass in the original unescaped query to `render_template` because that will break things (I think in `highlight(query)` in `list.html`). So I will make a new issue for resolving this

**Comment by trbedwards** [comment]
@robintw I think we can close this now. I haven't yet figure out how to do proper unit tests for these sort of paths, but from the manual tests I've done it seems to work

**Comment by robintw** [comment]
Thanks @trbedwards that's great.

To merge this I'll need you to open another Pull Request (PR) - hopefully there will be a button to do it when you go to www.recipy.org, but if not then you might need to go to your fork of recipy and find a 'create pull request' button. You should then be able to select a branch and get it to do the comparisons and create the PR.

(To avoid this in future, you can create a new branch - with `git checkout -b branch-name` - for each separate thing you fix, and that'll make it really easy to do the PR)

**Comment by trbedwards** [comment]
@robintw OK cool, I'll bear that in mind in the future. I've created a pull request in issue #160

**Comment by robintw** [comment]
Fixed by #160.
