### ISSUE TITLE
Add 'annotate' functionality

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#69]
This was suggested to me earlier by someone - can't remember who. The idea would be to be able to annotate particular runs in the database by adding to a `notes` field, or something similar.

I can see a command like: 

`recipy annotate` which brings up a text editor (like `git commit` does), and which does the latest run by default but allows you to set which run to edit with the run ID or another search term (eg with `--run` options).

In terms of the GUI I'm not entirely sure, but it'd be good if there was some way of clicking a button to annotate, and then editing some text and saving it in the field.

Do you think it's worth having a look at this? I'm happy to do the command-line interface, would you be able to look at the GUI side of things @jvdzwaan?

**Comment by jvdzwaan** [comment]
Sure. This wouldn't be to hard to add.

**Comment by jvdzwaan** [comment]
So, in the GUI runs can be annotated with notes. Notes are also searched when searching for runs.

**Comment by robintw** [comment]
Thanks @jvdzwaan, that's great! I just need to get round to doing the same for the CLI now...!

**Comment by jvdzwaan** [comment]
Hmmm, I added a notes field, but we already have an unused description field (at least, I think it is currently unused). Shall I remove the notes field and use the description field instead? What do you think, @robintw?

**Comment by robintw** [comment]
I didn't realise we had a description field, but you're right, we do have one and it isn't used. I'd probably prefer to call it `notes` (makes it clearer that it is just an optional field for any notes, rather than a required description), but what do you think? We could just delete the `description` field - it's only defined as `""` in a few places.

**Comment by jvdzwaan** [comment]
'Notes' does sound more optional than 'description', so let's stick to notes and remove description.

**Comment by robintw** [comment]
I've done a first go of annotation for the CLI in 94d8ae2.

I'm looking for advice on how the CLI should work. At the moment I have `recipy annotate` which annotates the latest run. Somehow I'd like to let users search for runs to annotate - but things get a bit confusing about how to do that given that we have various sub-commands: `recipy latest` and `recipy search` for example.

Any ideas? Or should I delay this to the next release and open an issue for command-line interface re-organisation?

**Comment by jvdzwaan** [comment]
I can see how things get complicated. Somehow it makes sense to just be able to annotate the latest run, but if you forget to do it when it is the latest run, why are you not able to annotate searches, etc. Perhaps annotating using a run id is a possibility, however, they are not easy to type. Also: what happens if you annotate a run twice? Is de comment added to what is already there or is is replaced? How about if some of the search results have already notes and some of them don't?

It would perhaps also be nice to be able to annotate the run from inside the script. Or maybe that doesn't make sense, because you don't want static information there.

I guess thinking about this some more is a good idea. It would also be nice what people want, how they want to be able to annotate.

**Comment by robintw** [comment]
This has been implemented, although more advanced functionality could be useful - so I've opened a separate issue for that #134.
