### ISSUE TITLE
Have recipy store complete code

### ISSUE THREAD

**Issue by HannoSpreeuw** [recipy/recipy#85]
Can one have recipy store the complete block of Python code - i.e. everything after "import recipy"?

**Comment by robintw** [comment]
I think the best thing to do to get this sort of functionality is to store your code in a source control system such as git. Then, recipy will log the current commit (plus other information about the repository itself), plus any changes that have occurred since the last commit (basically the output of `git diff`).

At the moment only git is supported, but we would be more than happy to look at adding support for other version control systems (SVN, Mercurial etc).

Does this sound like it would solve your problem? I'm wary of adding features to recipy which I think are probably better found in source control systems.

**Comment by HannoSpreeuw** [comment]
The most likely answer! But storing source code without the burden of implementing and managing a version control system can be handy, although I agree that this is not the most elegant approach.

**Comment by jvdzwaan** [comment]
You are not implying you don't use version control, are you Hanno?

**Comment by HannoSpreeuw** [comment]
Eh, you got me there!

**Comment by robintw** [comment]
Closing in favour of using version control.
