### ISSUE TITLE
tinydb error

### ISSUE THREAD

**Issue by codemeleon** [recipy/recipy#92]
Hi,

When I import recipy I get following errors.
In [1]: import recipy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-dde966f4f984> in <module>()
----> 1 import recipy

/anaconda3/lib/python3.5/site-packages/recipy/__init__.py in <module>()
      1 # These two lines ARE needed, as they actually set up sys.meta_path
----> 2 from . import PatchBaseScientific
      3 from . import PatchScientific
      4 
      5 from .log import *

/anaconda3/lib/python3.5/site-packages/recipy/PatchBaseScientific.py in <module>()
      1 import sys
----> 2 from .PatchImporter import PatchImporter
      3 from .PatchSimple import PatchSimple
      4 import wrapt
      5 

/anaconda3/lib/python3.5/site-packages/recipy/PatchImporter.py in <module>()
      4 import functools
      5 from recipyCommon.config import option_set
----> 6 from recipyCommon.utils import recursive_find_module
      7 
      8 class PatchImporter(object):

/anaconda3/lib/python3.5/site-packages/recipyCommon/utils.py in <module>()
      4 
      5 from tinydb import TinyDB
----> 6 from .tinydb_serialization import serialization
      7 
      8 from .config import get_db_path

/anaconda3/lib/python3.5/site-packages/recipyCommon/tinydb_serialization.py in <module>()
      2 
      3 from tinydb.storages import JSONStorage
----> 4 from tinydb.serialize import Serializer
      5 from tinydb.middlewares import SerializationMiddleware
      6 

ImportError: No module named 'tinydb.serialize'

Thanks

**Comment by robintw** [comment]
Thanks for reporting this error. It seems to be due to some changes that have occurred in the latest version of TinyDB (see http://tinydb.readthedocs.org/en/latest/changelog.html#v3-0-0-2015-11-13).

I thought that it would be very simple to fix recipy to work with the new version of TinyDB, but unfortunately there seem to be some issues installing the new version. I'm liaising with the author of TinyDB about this (see https://github.com/msiemens/tinydb-serialization/issues/1), and will hopefully be able to solve it shortly.

**Comment by robintw** [comment]
This has now been fixed in TinyDB, and the relevant changes incorporated into recipy in 0422f80. I will be pushing a new version to PyPI very shortly, and you should be able to run `pip install -U recipy` to upgrade

**Comment by codemeleon** [comment]
Many thanks for fixing the bug.
